apiVersion: v2
name: bucketup
description: Serves GCS bucket content via simple HTTP server
home: https://github.com/bosbaber/bucketup

type: application
# Gets replaced during release
version: 1.0.0 
# Gets replaced during release
appVersion: "v1.0.0" 

dependencies:
  - name: common
    version: 0.9.0
    repository: https://interledger.github.io/charts/interledger

maintainers:
  - name: Stephan Butler
    email: stephan@interledger.foundation
