bucketName: "bucketup-sample"

replicaCount: 2

service:
  - name: service
    type: ClusterIP
    annotations: {}
    ports:
      - port: 8080
        targetPort: 8080
        protocol: TCP
        name: http

concurrency:
  group: main
  cancel-in-progress: true
  max: 1

