bucketName: "bucketup-bucket"

service:
  - name: service
    type: ClusterIP
    annotations: {}
    ports:
      - port: 8080
        targetPort: 8080
        protocol: TCP
        name: http

containers:
  - name: server
    image:
      repository: ghcr.io/bosbaber
      name: bucketup
      pullPolicy: Always
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 1
    ports:
      - name: http
        containerPort: 8080
        protocol: TCP