bucketName: "bucketup-sample"

replicaCount: 2

service:
  - name: service
    type: ClusterIP
    annotations: {}
    ports:
      - port: 8080
        targetPort: 8080
        protocol: TCP
        name: http

concurrency:
  group: main
  cancel-in-progress: true
  max: 1

containers:
  - name: server
    image:
      repository: ghcr.io/bosbaber
      name: bucketup
      pullPolicy: Always
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 1
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
    ports:
      - name: http
        containerPort: 8080
        protocol: TCP