# Test overrides for CI: avoid GCS, serve a simple static page
containers:
  - name: server
    image:
      repository: ghcr.io/bosbaber
      name: bucketup
      tag: ci
      pullPolicy: Never
    ports:
      - name: http
        containerPort: 8080
        protocol: TCP