{{- include "common.deployment" (list . .Values .Values.autoscaling .Values.serviceAccount "bucketup.deployment") }}

containers:
  - name: server
    image:
      repository: ghcr.io/bosbaber
      name: bucketup
      pullPolicy: Always
    envFrom:
      - configMapRef:
          name: {{ include "common.fullname" . }}
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 1
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
    ports:
      - name: http
        containerPort: 8080
        protocol: TCP

{{- define "bucketup.deployment" -}}
{{- end }}
